### ISSUE TITLE
Add competitive coding problems and solutions in JAVA

### ISSUE THREAD

**Issue by srsandy** [srsandy/Data-Structures-and-Algorithms-in-Java-2nd-Edition-by-Robert-Lafore#62]
Add a PR with any competitive coding problem
In
- [/Practice Problems/](https://github.com/srsandy/Data-Structures-and-Algorithms-in-Java-2nd-Edition-by-Robert-Lafore/tree/master/Practice%20Problems/) add competitive coding problems and solutions in the respective topic folder

Check other folders in `Arrays` how it is done in rest of file 

E.g
- Add a folder in `Arrays` folder with the *Name of Problem Title*.
- Inside that folder add the solution `ProblemTitle.java` and a `README.md` 
- Make sure the class name is `ProblemTitle` that is the name of the file.
- `README.md` must contain a detail description of the problem with the test cases.

**Comment by Ishita-Mehta** [comment]
Hi! I'll trying for this issue. First for patterns programming problems. Have a good day!

**Comment by Ishita-Mehta** [comment]
Hi Sir! I've made 3 pull requests to your repository. I am participating in the Hacktoberfest 2020. There is a new update from digital ocean for maintainers. You can view the update here https://hacktoberfest.digitalocean.com/hacktoberfest-update It states :
We will honor all valid pull requests prior to this change, and as of October 3, 2020 at 12:00:00 UTC – and October 3 in all time zones – pull requests will only count toward earning a T-shirt or planting a tree if they are submitted in a repository classified with the ‘hacktoberfest’ topic. The pull requests will also need to be merged, approved by a maintainer, or labeled as ‘hacktoberfest-accepted’ in order to qualify. The deadline for completions, merging, labeling, and approving is November 1.
PRs count if: 
Submitted in a repo with the hacktoberfest topic AND 
during the month of October AND ( 
  The PR is merged OR 
  The PR is labelled as hacktoberfest-accepted by a maintainer OR 
  The PR has been approved 
)
Sir please help for the same. Thank you so much!

**Comment by Shaurya026** [comment]
Add hacktoberfest to the topics please or the PRs won't be counted, please @srsandy

**Comment by Ishita-Mehta** [comment]
Yes @srsandy Please add hacktoberfest to topics as currently its showing as repository Ineligible.

**Comment by srsandy** [comment]
@Ishita-Mehta @Shaurya026 
![Screen Shot 2020-10-03 at 7 45 25 PM](https://user-images.githubusercontent.com/21126403/94993789-023f8680-05b1-11eb-814b-6eec1e316303.png)

**Comment by Ishita-Mehta** [comment]
Thank you! 🙏
